language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - DB=mysql CAKEPHP=master
  - DB=mysql CAKEPHP=2.4

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - git clone git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp && git checkout $CAKEPHP
  - cp -R ../IMCake ./app/Plugin/
  - chmod -R 777 ./app/tmp
  - echo "<?php
    class DATABASE_CONFIG {
    public \$default = array(
      'datasource' => 'Database/Mysql',
      'persistent' => false,
      'host' => '0.0.0.0',
      'login' => 'root',
      'password' => '',
      'database' => 'cakephp_test',
      'prefix' => ''
    );
    public \$test = array(
      'datasource' => 'Database/Mysql',
      'persistent' => false,
      'host' => '0.0.0.0',
      'login' => 'root',
      'password' => '',
      'database' => 'cakephp_test',
      'prefix' => '',
      'encoding' => 'utf8'
    );
    }" > ./app/Config/database.php
  - echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
    <phpunit bootstrap=\"vendor/autoload.php\">
    <filter>
        <blacklist>
            <directory suffix=\".php\">app/Config</directory>
            <directory suffix=\".php\">app/Controller</directory>
            <directory suffix=\".php\">app/Model</directory>
            <directory suffix=\".php\">app/Test</directory>
            <directory suffix=\".php\">app/Vendor</directory>
            <directory suffix=\".php\">app/Plugin/IMCake/Test</directory>
            <directory suffix=\".php\">lib</directory>
            <directory suffix=\".php\">vendor</directory>
        </blacklist>
    </filter>
    </phpunit>
    " > ./phpunit.xml.dist
  - mv ./app/Plugin/IMCake/coveralls.json ./composer.json
  - mv ./app/Plugin/IMCake/.coveralls.yml ./.coveralls.yml
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction --prefer-source
  - mkdir -p build/logs

script:
  - ./lib/Cake/Console/cake test IMCake Controller/Component/IMCakeComponent --stderr --coverage-clover build/logs/clover.xml --configuration phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v