language: php

php:
  - 5.3
  - 5.4

env:
  - DB=mysql CAKEPHP=2.3.4

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - git clone git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp && git checkout $CAKEPHP
  - cp -R ../IMCakeComponent ./app/Plugin/IMCake
  - chmod -R 777 ./app/tmp
  - echo "<?php
    class DATABASE_CONFIG {
    public \$default = array(
      'datasource' => 'Database/Mysql',
      'persistent' => false,
      'host' => '0.0.0.0',
      'login' => 'root',
      'password' => '',
      'database' => 'cakephp_test',
      'prefix' => ''
    );
    public \$test = array(
      'datasource' => 'Database/Mysql',
      'persistent' => false,
      'host' => '0.0.0.0',
      'login' => 'root',
      'password' => '',
      'database' => 'cakephp_test',
      'prefix' => '',
      'encoding' => 'utf8'
    );
    }" > ./app/Config/database.php

script:
  - ./lib/Cake/Console/cake test IMCake Controller/Component/IMCakeComponent --stderr